openapi: 3.1.0
info:
  title: API Credicarro
  description: API para gerenciamento de cobranças e pagamentos usando o Credicarro.
  version: 1.0.0
servers:
  - url: https://api.staging.credicarro.com.br/integration
    description: Servidor para o ambiente de staging
paths:
  /v1/proposal:
    get:
      tags:
        - Proposta
      summary: Paginação de propostas
      description:  Paginação de todas as propostas associadas ao parceiro
      parameters:
        - name: offset
          in: query
          description: Offset/página inicial (mínimo 1).
          schema:
            type: integer
            format: int32
            example: 1
          example: 1
        - name: limit
          in: query
          description: Quantidade de itens por página (1 a 100).
          schema:
            type: integer
            format: int32
            example: 10
          example: 10
      responses:
        '200':
          description: Lista de propostas retornada com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  itens:
                    type: array
                    description: Lista de propostas.
                    items:
                      $ref: "#/components/schemas/ProposalResponse"
                  pagina:
                    $ref: "#/components/schemas/Page"
        '400':
          description: Erro na requisição
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
components:
  schemas:
    ProposalResponse:
      type: object
      description: Os dados da sua proposta.
      properties:
        id_proposta:
          type: string
          format: uuid
          description: Identificador único da proposta
          example: bea8d060-f93d-48eb-b6c4-45f64483cdd9
        numero:
          type: integer
          format: int64
          description: Número único da proposta.
          example: 171020250001
        id_simulacao:
          type: string
          format: uuid
          description: Identificador único da simulação
          example: bea8d060-f93d-48eb-b6c4-45f64483cdd9
        tipo:
          type: string
          description: Tipo da proposta utilizada
          enum: ['Finaning', 'Refinancing']
          example: Finaning
        status:
          type: string
          description: Status atual da proposta
          enum: ['Analysing', 'Approved', 'Refused', 'Canceled', 'ManualAnalysis', 'Completed', 'InNegotiation', 'Expired']
          example: Approved
        comprador:
          $ref: "#/components/schemas/Buyer"
        vendedor:
          $ref: "#/components/schemas/Seller"
        data_criacao:
          type: string
          format: date-time
          example: 2025-10-17T19:05:08.984Z
      additionalProperties: false
    Buyer:
      type: object
      properties:
        cpf:
          type: string
          description: Documento de identificação do comprador
          example: 123.456.789-01
      additionalProperties: false
    Seller:
      type: object
      properties:
        cpf:
          type: string
          description: Documento de identificação do vendedor
          example: 123.456.789-01
      additionalProperties: false
    Page:
      type: object
      properties:
        tem_proximo:
          type: boolean
          description: Identificador se existe uma próxima página
          example: true
        tem_anterior:
          type: boolean
          description: Identificador se existe uma página anterior
          example: false
        numero:
          type: integer
          format: int32
          description: Página atual.
          example: 2
        tamanho:
          type: integer
          format: int32
          description: Quantidade de dados por página.
          example: 15
        total:
          type: integer
          format: int64
          description: Total de dados encontrados.
          example: 45
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          description: Tipo de problema encontrado
          example: Partner.AccountIsIncompleted
        title:
          type: string
          description: Título do erro
          example: Bad Request
        status:
          type: integer
          format: int32
          description: Status Code do erro
          example: 400
        detail:
          type: string
          description: Descrição do erro
          example: Cadastro de conta não finalizado
        error:
          type: 'null'
      additionalProperties: false
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Cabeçalho de autenticação Bearer no formato `Bearer <credicarro-api-key>` onde `<credicarro-api-key>` é a sua chave de API. 